version: '3.8'

services:
  python-app:
    build:
      context: app/
      dockerfile: ./Dockerfile
    container_name: watanabe-python-app
    volumes:
      - .:/app
    working_dir: /app
    ports:
      - "8000:8000"

  db:
    image: mysql:8.0.28
    container_name: db
    platform: linux/amd64
    build:
      context: db/
      dockerfile: ./Dockerfile
    ports:
      - "3306:3306"
    environment:
      MYSQL_USER: user
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: demo
      TZ: "Asia/Tokyo"
    volumes:
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    profiles:
      - optional


